[package]
name = "tribal-db"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
tribal-domain.workspace = true
sqlx = { workspace = true, features = ["migrate"] }
pgvector.workspace = true
thiserror.workspace = true
tracing.workspace = true
