//! The driver family's transitions: suspend-with-child, child terminal,
//! and deferred death.
//!
//! A deferred tool's work is another thread. Three composed transitions
//! carry the lifecycle, each one atomic so a crash leaves no half-state:
//!
//! - **Suspend-with-child** commits, in one transaction: the parent's
//!   suspension record, its thread CAS to suspended, its stage task to
//!   blocked, the child thread, and the child's paired driver task. The
//!   child/driver pair relies on the deferred foreign key (the thread
//!   row names the driver task's id before the task exists), so nothing
//!   deferred is durable before the suspension that awaits it.
//! - **The child terminal** commits, in one transaction: the child's
//!   assistant record, its completion, the driver task's completion, the
//!   parent's fenced tool-result carrying the verdict, and the parent's
//!   resolution (running again, stage task re-queued). A parent no
//!   longer waiting (cancelled, already resolved) is the orphan window:
//!   the child and driver still complete, and the hand-back is discarded
//!   under the parent row lock: never resurrecting the parent, never
//!   double-committing.
//! - **Deferred death** owns the child terminal too: when the driver's
//!   retries exhaust, one transaction dead-letters the child and its
//!   driver task and crosses the permanent failure into the parent's
//!   conversation as an error tool-result, then resolves the parent. The
//!   child never outlives its driver row, so no janitor must hunt it.
//!
//! Orphan windows (a live child behind a terminal parent) are bounded
//! by the same parent row lock every terminal takes: the child runs to
//! its own terminal, finds the parent gone, and discards. The
//! availability sweep's cancel fallback reaches a child still suspended
//! when its parent vanished.

use sqlx::PgConnection;
use tribal_db::{
    AgentDriverTaskRepository, AgentThreadRecordRepository, AgentThreadRepository, DrivingTaskRef,
    NewAgentDriverTask, NewAgentThread, NewAgentThreadRecord, PgAgentDriverTaskRepository,
    PgAgentThreadRecordRepository, PgAgentThreadRepository, PgTaskRepository,
    PgTokenUsageRepository, TaskRepository, TokenUsageRepository,
};
use tribal_domain::{
    AgentBindingVersionId, AgentDriverTaskId, AgentDriverTaskKind, AgentThread, AgentThreadId,
    AgentThreadRecordKind, AgentThreadRecordSeq, AgentThreadStatus, AgentThreadSuspension,
    AgentThreadTerminal, CompletionResponse, JobId, PrincipalId, TaskId, TaskType, span_attrs,
};
use tribal_telemetry::{current_span_id, current_trace_id};

use crate::{
    AgentRuntimeError,
    turn::{AssistantContent, RecordedUsage, RenderedConversation},
    turn_loop::ToolResultContent,
    txn::{begin, commit},
};

// ---------------------------------------------------------------------------
// Suspend with child
// ---------------------------------------------------------------------------

/// The child a suspend-with-child launches: its binding, stage, and the
/// principal it is metered to. The driver task id is generated by the
/// transition.
#[derive(Debug, Clone, Copy)]
pub struct ChildLaunch {
    /// The stage the child executes (a verifier shares its parent's).
    pub pipeline_stage: TaskType,
    /// The content-addressed binding the child runs under.
    pub binding_version_id: AgentBindingVersionId,
    /// The principal the child is attributed and metered to.
    pub principal_id: PrincipalId,
    /// The job the child's spend meters to, captured from the parent so a
    /// reclaimed driver attributes without walking a possibly-terminal
    /// lineage. Absent when the parent runs outside a pipeline job.
    pub job_id: Option<JobId>,
    /// The serialisation shape of the child's owned structures.
    pub format_version: u32,
}

/// The pair a suspend-with-child created, for the driver loop to drive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LaunchedChild {
    /// The child thread, queued.
    pub thread_id: AgentThreadId,
    /// Its paired driver task.
    pub driver_task_id: AgentDriverTaskId,
}

/// What a suspend-with-child concluded.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SuspendWithChildOutcome {
    /// The parent suspended and the child/driver pair committed.
    Launched(LaunchedChild),
    /// The parent-status CAS refused: a durable cancellation intent (or a
    /// rival status move) intervened; nothing committed, and the caller
    /// performs the cancel transaction at this boundary.
    CancelIntervened,
}

/// Suspends a stage-driven parent on a pending tool call and launches the
/// child that will answer it, all in one transaction.
///
/// The pending call's id rides the suspension payload; resolution is
/// completeness-checked against it. The child thread names its driver
/// task's id under the deferred foreign key, so the pair commits
/// together with no insert order to satisfy eagerly.
///
/// # Errors
///
/// Returns [`AgentRuntimeError::LeaseLost`] when the parent's stage-task
/// block misses (nothing committed), plus the serialisation and database
/// errors of the parts.
// The transition's full guard and launch context; a params struct would
// only move the same arguments behind a name.
#[allow(clippy::too_many_arguments)]
pub async fn suspend_with_child(
    conn: &mut PgConnection,
    parent: &AgentThread,
    stage_task_id: TaskId,
    claim_token: uuid::Uuid,
    requesting_seq: AgentThreadRecordSeq,
    pending_tool_call_id: &str,
    launch: ChildLaunch,
    child_input: &RenderedConversation,
) -> Result<SuspendWithChildOutcome, AgentRuntimeError> {
    let suspension = AgentThreadSuspension::DeferredToolResults {
        requesting_seq,
        pending_tool_call_ids: vec![pending_tool_call_id.to_owned()],
    };
    let content = serialise_suspension(parent, &suspension)?;
    // The child is born with its conversation: the caller renders the
    // input (a verifier's rubric and the submission), and the driver loop
    // adopts it rather than re-rendering, the one-shot bracket's contract.
    let child_input_content = serde_json::to_value(child_input)
        .map_err(|source| serialisation(parent, "the child's input record", source))?;

    let mut txn = begin(conn, "beginning the suspend-with-child transaction").await?;

    // Lock order: the driving task's row first (the claim guard's write),
    // then the parent thread for the seq derivation and status CAS, then
    // the child rows.
    let blocked = PgTaskRepository
        .block(&mut txn, stage_task_id, claim_token)
        .await
        .map_err(|source| AgentRuntimeError::database("blocking the parent's task", source))?;
    if blocked == 0 {
        return Err(AgentRuntimeError::LeaseLost {
            driving_task: DrivingTaskRef::Stage(stage_task_id),
        });
    }

    PgAgentThreadRepository
        .lock(&mut txn, parent.id())
        .await
        .map_err(|source| AgentRuntimeError::database("locking the parent for suspend", source))?;
    let seq = next_seq(&mut txn, parent.id()).await?;
    PgAgentThreadRecordRepository
        .append(
            &mut txn,
            &NewAgentThreadRecord::builder()
                .thread_id(parent.id())
                .seq(seq)
                .kind(AgentThreadRecordKind::Suspension)
                .content(content)
                .trace_id(current_trace_id())
                .span_id(current_span_id())
                .build(),
        )
        .await
        .map_err(|source| {
            AgentRuntimeError::database("committing the suspension record", source)
        })?;

    let moved = PgAgentThreadRepository
        .suspend(&mut txn, parent.id(), &suspension, None)
        .await
        .map_err(|source| AgentRuntimeError::database("suspending the parent", source))?;
    if moved == 0 {
        // The CAS clause covers a durable cancel intent (or a rival
        // status move); nothing commits, and the caller performs the
        // cancel transaction at this boundary.
        return Ok(SuspendWithChildOutcome::CancelIntervened);
    }

    // The pair: the thread names the driver task's id under the deferred
    // FK, then the driver task takes that id, and the deferred check
    // passes at commit.
    let driver_task_id = AgentDriverTaskId::new();
    let child = PgAgentThreadRepository
        .insert(
            &mut txn,
            &NewAgentThread::builder()
                .parent_thread_id(Some(parent.id()))
                .pipeline_stage(launch.pipeline_stage)
                .binding_version_id(launch.binding_version_id)
                .driving_task(DrivingTaskRef::Driver(driver_task_id))
                .principal_id(launch.principal_id)
                .job_id(launch.job_id)
                .format_version(launch.format_version)
                .build(),
        )
        .await
        .map_err(|source| AgentRuntimeError::database("creating the child thread", source))?;
    PgAgentDriverTaskRepository
        .insert(
            &mut txn,
            &NewAgentDriverTask::builder()
                .id(Some(driver_task_id))
                .thread_id(child.id())
                .kind(AgentDriverTaskKind::Drive)
                .build(),
        )
        .await
        .map_err(|source| AgentRuntimeError::database("enrolling the child driver task", source))?;

    PgAgentThreadRecordRepository
        .append(
            &mut txn,
            &NewAgentThreadRecord::builder()
                .thread_id(child.id())
                .seq(AgentThreadRecordSeq::FIRST)
                .kind(AgentThreadRecordKind::Input)
                .content(child_input_content)
                .trace_id(current_trace_id())
                .span_id(current_span_id())
                .build(),
        )
        .await
        .map_err(|source| {
            AgentRuntimeError::database("committing the child's input record", source)
        })?;

    commit(txn, "committing the suspend-with-child transaction").await?;
    tracing::info!(
        { span_attrs::SUSPENSION_REASON } = suspension.reason_label(),
        { span_attrs::REQUESTING_SEQ } = requesting_seq.inner(),
        "agentic thread suspended on a deferred tool result",
    );
    tracing::info!(
        { span_attrs::CHILD_BINDING_VERSION } = %launch.binding_version_id,
        { span_attrs::CHILD_STAGE } = launch.pipeline_stage.as_str(),
        { span_attrs::REQUESTING_SEQ } = requesting_seq.inner(),
        "agentic verifier child launched",
    );
    Ok(SuspendWithChildOutcome::Launched(LaunchedChild {
        thread_id: child.id(),
        driver_task_id,
    }))
}

// ---------------------------------------------------------------------------
// Child terminal and deferred death
// ---------------------------------------------------------------------------

/// What a child terminal (success or death) concluded for the parent.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChildTerminalOutcome {
    /// The verdict was handed back: the parent woke and re-queued.
    HandedBack,
    /// The parent was no longer waiting (terminal, or already resolved):
    /// the child and driver completed, the hand-back discarded under the
    /// parent row lock.
    ParentNotWaiting,
}

impl ChildTerminalOutcome {
    /// The telemetry label for a child terminal's outcome for its parent.
    fn label(self) -> &'static str {
        match self {
            Self::HandedBack => span_attrs::CHILD_TERMINAL_HANDED_BACK,
            Self::ParentNotWaiting => span_attrs::CHILD_TERMINAL_PARENT_NOT_WAITING,
        }
    }
}

/// The parent a child resolves into: the suspended thread, the call its
/// result answers, and the stage task to re-queue on the hand-back.
#[derive(Debug, Clone)]
pub struct ParentResolution {
    /// The suspended parent thread's id.
    pub thread_id: AgentThreadId,
    /// The assistant message whose call the child answers.
    pub requesting_seq: AgentThreadRecordSeq,
    /// The pending call id the result fences against.
    pub tool_call_id: String,
}

/// Commits a child's successful terminal: the child's assistant record
/// and completion, the driver task's completion, and the parent's fenced
/// tool-result carrying `verdict`, then resolves the parent.
///
/// The driver-task completion is the claim guard: a stale token (a
/// reclaimed task) affects zero rows and the whole commit rolls back, so
/// a reclaimed run can never hand back twice. A parent no longer
/// suspended is the orphan window: the child and driver still complete,
/// the hand-back discards.
///
/// # Errors
///
/// Returns [`AgentRuntimeError::LeaseLost`] when the driver claim misses,
/// plus the serialisation and database errors of the parts.
// The terminal's full guard and hand-back context; a params struct would
// only move the same arguments behind a name.
#[allow(clippy::too_many_arguments)]
pub async fn commit_child_terminal(
    conn: &mut PgConnection,
    child: &AgentThread,
    driver_task_id: AgentDriverTaskId,
    driver_claim_token: uuid::Uuid,
    attempt: i32,
    child_response: &CompletionResponse,
    parent: &ParentResolution,
) -> Result<ChildTerminalOutcome, AgentRuntimeError> {
    // `hand_back` locks the parent thread before its task, the sanctioned
    // inversion of the global lock order it needs to read the parent's
    // suspended status as the orphan guard. Correctness rests on bounded
    // retry: a deadlock abort against an opposing-order writer retries the
    // whole transaction in place rather than re-driving the child (a fresh
    // verifier model call) or, on the final attempt, discarding a good
    // verdict into a deferred-death error. The loop is inline because each
    // attempt reborrows the connection, which a closure cannot hold across
    // calls.
    let mut remaining = CHILD_TERMINAL_CONFLICT_RETRIES;
    loop {
        match commit_child_terminal_once(
            conn,
            child,
            driver_task_id,
            driver_claim_token,
            attempt,
            child_response,
            parent,
        )
        .await
        {
            Err(e) if remaining > 0 && e.is_retryable() => {
                remaining -= 1;
                tracing::warn!(
                    child_thread_id = %child.id(),
                    { span_attrs::CONFLICT_RETRY_REMAINING } = remaining,
                    "child-terminal commit hit a transient conflict; retrying in place",
                );
            }
            Ok(outcome) => {
                tracing::info!(
                    child_thread_id = %child.id(),
                    { span_attrs::CHILD_TERMINAL_OUTCOME } = outcome.label(),
                    { span_attrs::DRIVER_ATTEMPT } = attempt,
                    { span_attrs::TERMINAL_IS_ERROR } = false,
                    "agentic child terminal committed",
                );
                return Ok(outcome);
            }
            err => return err,
        }
    }
}

/// Attempts at the child-terminal commit before a persistent conflict
/// surfaces, matching the shared [`retry_on_conflict`] budget.
const CHILD_TERMINAL_CONFLICT_RETRIES: u32 = 5;

// The same guard and hand-back context as the wrapper; a params struct would
// only move the same arguments behind a name.
#[allow(clippy::too_many_arguments)]
async fn commit_child_terminal_once(
    conn: &mut PgConnection,
    child: &AgentThread,
    driver_task_id: AgentDriverTaskId,
    driver_claim_token: uuid::Uuid,
    attempt: i32,
    child_response: &CompletionResponse,
    parent: &ParentResolution,
) -> Result<ChildTerminalOutcome, AgentRuntimeError> {
    let mut txn = begin(conn, "beginning the child-terminal transaction").await?;

    complete_driver_task(&mut txn, driver_task_id, driver_claim_token).await?;
    finish_child(
        &mut txn,
        child,
        Some((child_response, attempt)),
        AgentThreadTerminal::Completed,
    )
    .await?;
    // The verdict is the child's raw structured response; the parent
    // loop reads it from the tool result and interprets it.
    let outcome = hand_back(
        &mut txn,
        parent,
        &ToolResultContent {
            output: child_response.text.clone(),
            is_error: false,
        },
    )
    .await?;

    commit(txn, "committing the child-terminal transaction").await?;
    Ok(outcome)
}

/// Commits a child's permanent failure: the child and its driver task
/// dead-lettered, and the failure crossed into the parent's conversation
/// as an error tool-result, then the parent resolved. The child never
/// outlives its driver row.
///
/// # Errors
///
/// Returns [`AgentRuntimeError::LeaseLost`] when the driver claim misses,
/// plus the serialisation and database errors of the parts.
pub async fn commit_deferred_death(
    conn: &mut PgConnection,
    child: &AgentThread,
    driver_task_id: AgentDriverTaskId,
    driver_claim_token: uuid::Uuid,
    parent: &ParentResolution,
    error_message: &str,
) -> Result<ChildTerminalOutcome, AgentRuntimeError> {
    let mut txn = begin(conn, "beginning the deferred-death transaction").await?;

    let dead_lettered = PgAgentDriverTaskRepository
        .dead_letter(&mut txn, driver_task_id, driver_claim_token, error_message)
        .await
        .map_err(|source| AgentRuntimeError::database("dead-lettering the driver task", source))?;
    if dead_lettered == 0 {
        return Err(AgentRuntimeError::LeaseLost {
            driving_task: DrivingTaskRef::Driver(driver_task_id),
        });
    }
    finish_child_status(&mut txn, child, AgentThreadTerminal::DeadLetter).await?;
    let outcome = hand_back(
        &mut txn,
        parent,
        &ToolResultContent {
            output: error_message.to_owned(),
            is_error: true,
        },
    )
    .await?;

    commit(txn, "committing the deferred-death transaction").await?;
    tracing::warn!(
        child_thread_id = %child.id(),
        { span_attrs::CHILD_TERMINAL_OUTCOME } = outcome.label(),
        { span_attrs::TERMINAL_IS_ERROR } = true,
        "agentic child deferred death committed",
    );
    Ok(outcome)
}

// ---------------------------------------------------------------------------
// Shared parts
// ---------------------------------------------------------------------------

/// Completes the driver task under its claim guard; a stale token rolls
/// the whole terminal back.
async fn complete_driver_task(
    txn: &mut PgConnection,
    driver_task_id: AgentDriverTaskId,
    claim_token: uuid::Uuid,
) -> Result<(), AgentRuntimeError> {
    let completed = PgAgentDriverTaskRepository
        .complete(txn, driver_task_id, claim_token)
        .await
        .map_err(|source| AgentRuntimeError::database("completing the driver task", source))?;
    if completed == 0 {
        return Err(AgentRuntimeError::LeaseLost {
            driving_task: DrivingTaskRef::Driver(driver_task_id),
        });
    }
    Ok(())
}

/// Appends the child's assistant record (when it produced one) and moves
/// it to its terminal, linking the child's committed spend to its record
/// under the thread-keyed attribution.
async fn finish_child(
    txn: &mut PgConnection,
    child: &AgentThread,
    response: Option<(&CompletionResponse, i32)>,
    terminal: AgentThreadTerminal,
) -> Result<(), AgentRuntimeError> {
    if let Some((response, attempt)) = response {
        let content = serde_json::to_value(AssistantContent {
            text: response.text.clone(),
            tool_calls: vec![],
        })
        .map_err(|source| serialisation(child, "the child's assistant content", source))?;
        let usage = serde_json::to_value(RecordedUsage::from(response))
            .map_err(|source| serialisation(child, "the child's usage", source))?;

        PgAgentThreadRepository
            .lock(txn, child.id())
            .await
            .map_err(|source| {
                AgentRuntimeError::database("locking the child for terminal", source)
            })?;
        let seq = next_seq(txn, child.id()).await?;
        let record = PgAgentThreadRecordRepository
            .append(
                txn,
                &NewAgentThreadRecord::builder()
                    .thread_id(child.id())
                    .seq(seq)
                    .kind(AgentThreadRecordKind::AssistantMessage)
                    .content(content)
                    .usage(Some(usage))
                    .trace_id(current_trace_id())
                    .span_id(current_span_id())
                    .build(),
            )
            .await
            .map_err(|source| {
                AgentRuntimeError::database("committing the child's assistant record", source)
            })?;
        // Thread-keyed attribution: the child has no stage task, so its
        // committed spend links to its record through the thread, under
        // the same single-most-recent-row constraint as the parent's.
        PgTokenUsageRepository
            .link_thread_completion_to_record(txn, child.id(), attempt, record.id())
            .await
            .map_err(|source| {
                AgentRuntimeError::database("linking the child's spend to its record", source)
            })?;
    }
    finish_child_status(txn, child, terminal).await
}

/// Moves the child to a terminal status. A death path carries no
/// assistant record (the child produced no result), so the status move
/// stands alone.
async fn finish_child_status(
    txn: &mut PgConnection,
    child: &AgentThread,
    terminal: AgentThreadTerminal,
) -> Result<(), AgentRuntimeError> {
    let moved = PgAgentThreadRepository
        .complete(txn, child.id(), terminal, AgentThreadStatus::Running)
        .await
        .map_err(|source| AgentRuntimeError::database("completing the child thread", source))?;
    if moved == 0 {
        return Err(AgentRuntimeError::StatusCasMissed {
            thread_id: child.id(),
            expected: AgentThreadStatus::Running,
        });
    }
    Ok(())
}

/// Hands the result back to the parent: under the parent row lock, a
/// suspended parent takes the fenced tool-result and wakes; a parent no
/// longer waiting discards the hand-back. The parent lock is the orphan
/// guard.
async fn hand_back(
    txn: &mut PgConnection,
    parent: &ParentResolution,
    result: &ToolResultContent,
) -> Result<ChildTerminalOutcome, AgentRuntimeError> {
    let Some(locked) = PgAgentThreadRepository
        .lock(txn, parent.thread_id)
        .await
        .map_err(|source| {
            AgentRuntimeError::database("locking the parent for hand-back", source)
        })?
    else {
        return Ok(ChildTerminalOutcome::ParentNotWaiting);
    };
    if locked.status() != AgentThreadStatus::Suspended {
        // The orphan window: a cancelled or already-resolved parent is
        // not waiting. The child and driver still committed above; the
        // hand-back discards.
        return Ok(ChildTerminalOutcome::ParentNotWaiting);
    }

    let content = serde_json::to_value(result).map_err(|source| {
        serialisation_id(parent.thread_id, "the hand-back tool result", source)
    })?;
    let seq = next_seq(txn, parent.thread_id).await?;
    PgAgentThreadRecordRepository
        .append(
            txn,
            &NewAgentThreadRecord::builder()
                .thread_id(parent.thread_id)
                .seq(seq)
                .kind(AgentThreadRecordKind::ToolResult)
                .requesting_seq(Some(parent.requesting_seq))
                .tool_call_id(Some(parent.tool_call_id.clone()))
                .content(content)
                .trace_id(current_trace_id())
                .span_id(current_span_id())
                .build(),
        )
        .await
        .map_err(|source| {
            AgentRuntimeError::database("committing the parent's hand-back result", source)
        })?;

    let woken = PgAgentThreadRepository
        .mark_running(txn, parent.thread_id, AgentThreadStatus::Suspended)
        .await
        .map_err(|source| AgentRuntimeError::database("waking the parent", source))?;
    if woken == 0 {
        return Err(AgentRuntimeError::StatusCasMissed {
            thread_id: parent.thread_id,
            expected: AgentThreadStatus::Suspended,
        });
    }
    if let Some(task_id) = locked.stage_task_id() {
        let rows = PgTaskRepository
            .requeue_from_blocked(txn, task_id)
            .await
            .map_err(|source| AgentRuntimeError::database("re-queueing the parent task", source))?;
        if rows == 0 {
            // The parent's task is blocked by construction while a child
            // drives, so a zero-row requeue would leave it running with an
            // unclaimable task; roll the hand-back back rather than strand
            // it.
            return Err(AgentRuntimeError::DrivingTaskNotBlocked { task_id });
        }
    }
    Ok(ChildTerminalOutcome::HandedBack)
}

async fn next_seq(
    txn: &mut PgConnection,
    thread_id: AgentThreadId,
) -> Result<AgentThreadRecordSeq, AgentRuntimeError> {
    PgAgentThreadRecordRepository
        .next_seq(txn, thread_id)
        .await
        .map_err(|source| AgentRuntimeError::database("deriving the next seq", source))
}

fn serialise_suspension(
    thread: &AgentThread,
    suspension: &AgentThreadSuspension,
) -> Result<serde_json::Value, AgentRuntimeError> {
    serde_json::to_value(suspension)
        .map_err(|source| serialisation(thread, "the suspension record", source))
}

fn serialisation(thread: &AgentThread, what: &str, source: serde_json::Error) -> AgentRuntimeError {
    serialisation_id(thread.id(), what, source)
}

fn serialisation_id(
    thread_id: AgentThreadId,
    what: &str,
    source: serde_json::Error,
) -> AgentRuntimeError {
    AgentRuntimeError::ContentSerialisation {
        context: format!("serialising {what} of thread {thread_id}"),
        source,
    }
}
