//! Factory functions for domain entity construction in tests.
//!
//! Every `a_`-prefixed factory returns a factory struct with chainable
//! setters and a `build()` method. Factory structs are generated by the
//! [`define_factory!`] macro and delegate to the entity's `TypedBuilder`
//! or `new()` constructor under the hood.
//!
//! ```rust,ignore
//! // Override only the fields relevant to your test:
//! let project = a_project().name("custom".to_owned()).build();
//! let principal = a_principal().principal_key("user:sam".to_owned()).build();
//! ```

// ---------------------------------------------------------------------------
// define_factory! macro — must precede submodule declarations so child
// modules inherit it.
// ---------------------------------------------------------------------------

/// Generates a factory struct with chainable setters and a `build()` method
/// that delegates to the entity's `TypedBuilder`.
///
/// Fields **must** be listed in the same order as the struct declaration
/// because `typed-builder` enforces sequential setter calls.
macro_rules! define_factory {
    (
        $(#[$meta:meta])*
        $vis:vis struct $factory:ident for $entity:ident {
            $( $field:ident : $ty:ty = $default:expr ),* $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        $vis struct $factory {
            $( $field: $ty, )*
        }

        impl Default for $factory {
            fn default() -> Self {
                Self::new()
            }
        }

        impl $factory {
            /// Creates a new factory with sensible defaults.
            pub fn new() -> Self {
                Self {
                    $( $field: $default, )*
                }
            }

            $(
                /// Overrides the default value for this field.
                #[must_use]
                pub fn $field(mut self, value: $ty) -> Self {
                    self.$field = value;
                    self
                }
            )*

            /// Builds the entity instance from current factory state.
            pub fn build(self) -> $entity {
                $entity::builder()
                    $( .$field(self.$field) )*
                    .build()
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Submodules — one per domain entity file, mirroring tribal-domain structure.
// ---------------------------------------------------------------------------

mod auth_token;
mod embedding;
mod item_observation;
mod job;
mod knowledge;
mod principal;
mod project;
mod prompt_version;
mod reference;
mod relation;
mod retrieval_feedback;
mod standing;
mod tag_registry;
mod task;
mod token_usage;
mod triage;

pub use auth_token::*;
pub use embedding::*;
pub use item_observation::*;
pub use job::*;
pub use knowledge::*;
pub use principal::*;
pub use project::*;
pub use prompt_version::*;
pub use reference::*;
pub use relation::*;
pub use retrieval_feedback::*;
pub use standing::*;
pub use tag_registry::*;
pub use task::*;
pub use token_usage::*;
pub use triage::*;
