//! Factory functions for domain entity construction in tests.
//!
//! Each factory is an `a_`-prefixed function (or `an_` when the name begins
//! with a vowel sound, e.g. `an_embedding`). It returns a factory struct
//! with chainable setters and a `build()` method. Factory structs are
//! generated by the [`define_factory!`] macro and delegate to the entity's
//! `TypedBuilder` under the hood.
//!
//! ```rust,ignore
//! // Override only the fields relevant to your test:
//! let project = a_project().name("custom".to_owned()).build();
//! let principal = a_principal().principal_key("user:sam".to_owned()).build();
//! ```

// ---------------------------------------------------------------------------
// define_factory! macro: must precede submodule declarations so child
// modules inherit it.
// ---------------------------------------------------------------------------

/// Generates a factory struct with chainable setters and a `build()` method
/// that delegates to the entity's `TypedBuilder`.
///
/// Fields are listed in the same order as the struct declaration
/// by convention, matching the source layout.
macro_rules! define_factory {
    (
        $(#[$meta:meta])*
        $vis:vis struct $factory:ident for $entity:ident {
            $( $field:ident : $ty:ty = $default:expr ),* $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        $vis struct $factory {
            $( $field: $ty, )*
        }

        impl Default for $factory {
            fn default() -> Self {
                Self::new()
            }
        }

        impl $factory {
            /// Creates a new factory with sensible defaults.
            pub fn new() -> Self {
                Self {
                    $( $field: $default, )*
                }
            }

            $(
                /// Overrides the default value for this field.
                #[must_use]
                pub fn $field(mut self, value: $ty) -> Self {
                    self.$field = value;
                    self
                }
            )*

            /// Builds the entity instance from current factory state.
            pub fn build(self) -> $entity {
                $entity::builder()
                    $( .$field(self.$field) )*
                    .build()
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Submodules: one per domain entity file, mirroring tribal-domain structure.
// ---------------------------------------------------------------------------

mod agent_binding;
mod agent_driver_task;
mod agent_thread;
mod auth_token;
mod candidate;
mod embedding;
mod embedding_profile;
mod extraction_result;
mod item_observation;
mod job;
mod knowledge;
mod principal;
mod project;
mod prompt_version;
mod reference;
mod relation;
mod retrieval_feedback;
mod standing;
mod system_fingerprint;
mod tag_embedding;
mod tag_registry;
mod task;
mod token_usage;
mod triage;

pub use agent_binding::*;
pub use agent_driver_task::*;
pub use agent_thread::*;
pub use auth_token::*;
pub use candidate::*;
pub use embedding::*;
pub use embedding_profile::*;
pub use extraction_result::*;
pub use item_observation::*;
pub use job::*;
pub use knowledge::*;
pub use principal::*;
pub use project::*;
pub use prompt_version::*;
pub use reference::*;
pub use relation::*;
pub use retrieval_feedback::*;
pub use standing::*;
pub use system_fingerprint::*;
pub use tag_embedding::*;
pub use tag_registry::*;
pub use task::*;
pub use token_usage::*;
pub use triage::*;

// ---------------------------------------------------------------------------
// Macro-level smoke test: verifies that generated setters override defaults.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_setter_overrides_default() {
        let project = a_project().name("custom".to_owned()).build();
        assert_eq!(project.name(), "custom");
        assert_eq!(project.default_branch(), "main");
    }
}
