//! Factory functions for domain entity construction in tests.
//!
//! Every `a_`-prefixed factory returns a factory struct with chainable
//! setters and a `build()` method. Factory structs are generated by the
//! [`define_factory!`] macro and delegate to the entity's `TypedBuilder`
//! or `new()` constructor under the hood.
//!
//! ```rust,ignore
//! // Override only the fields relevant to your test:
//! let project = a_project().name("custom".to_owned()).build();
//! let principal = a_principal().principal_key("user:sam".to_owned()).build();
//! ```

use chrono::Utc;
use tribal_domain::{
    AuthToken, AuthTokenId, Confidence, Embedding, EmbeddingId, FeedbackRating, ItemObservation,
    ItemObservationId, Job, JobId, JobStatus, KnowledgeItem, KnowledgeItemId,
    KnowledgeItemRelation, KnowledgeKind, PipelineStage, Principal, PrincipalId, Project,
    ProjectId, PromptStage, PromptVersion, PromptVersionId, Reference, ReferenceId, ReferenceKind,
    RelationBatchId, RelationId, RelationKind, RelationSuggestion, RetrievalFeedback,
    RetrievalFeedbackId, SimilarItem, SourceType, Standing, TagRegistryEntry, Task, TaskId,
    TaskStatus, TaskType, TokenUsage, TokenUsageId, TriageOutcome, TriageResult, TriageResultId,
    TriageSimilarItemDecision, TriageSimilarItemDecisionId,
};

// ---------------------------------------------------------------------------
// define_factory! macro
// ---------------------------------------------------------------------------

/// Generates a factory struct with chainable setters and a `build()` method
/// that delegates to the entity's `TypedBuilder`.
///
/// Fields **must** be listed in the same order as the struct declaration
/// because `typed-builder` enforces sequential setter calls.
macro_rules! define_factory {
    (
        $(#[$meta:meta])*
        $vis:vis struct $factory:ident for $entity:ident {
            $( $field:ident : $ty:ty = $default:expr ),* $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        $vis struct $factory {
            $( $field: $ty, )*
        }

        impl Default for $factory {
            fn default() -> Self {
                Self::new()
            }
        }

        impl $factory {
            /// Creates a new factory with sensible defaults.
            pub fn new() -> Self {
                Self {
                    $( $field: $default, )*
                }
            }

            $(
                /// Overrides the default value for this field.
                #[must_use]
                pub fn $field(mut self, value: $ty) -> Self {
                    self.$field = value;
                    self
                }
            )*

            /// Builds the entity instance from current factory state.
            pub fn build(self) -> $entity {
                $entity::builder()
                    $( .$field(self.$field) )*
                    .build()
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Factory-struct factories
// ---------------------------------------------------------------------------

define_factory! {
    /// Factory for [`Principal`] instances.
    pub struct PrincipalFactory for Principal {
        id: PrincipalId = PrincipalId::new(),
        principal_key: String = "user:test".to_owned(),
        display_name: Option<String> = None,
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`PrincipalFactory`] with sensible defaults.
pub fn a_principal() -> PrincipalFactory {
    PrincipalFactory::new()
}

define_factory! {
    /// Factory for [`TagRegistryEntry`] instances.
    pub struct TagRegistryEntryFactory for TagRegistryEntry {
        tag: String = "test-tag".to_owned(),
        first_seen_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`TagRegistryEntryFactory`] with sensible defaults.
pub fn a_tag_registry_entry() -> TagRegistryEntryFactory {
    TagRegistryEntryFactory::new()
}

define_factory! {
    /// Factory for [`SimilarItem`] instances.
    pub struct SimilarItemFactory for SimilarItem {
        item_id: KnowledgeItemId = KnowledgeItemId::new(),
        similarity_score: f32 = 0.85,
        suggested_relation: RelationSuggestion = RelationSuggestion::Supports,
    }
}

/// Returns a [`SimilarItemFactory`] with sensible defaults.
pub fn a_similar_item() -> SimilarItemFactory {
    SimilarItemFactory::new()
}

define_factory! {
    /// Factory for [`Project`] instances.
    pub struct ProjectFactory for Project {
        id: ProjectId = ProjectId::new(),
        git_remote: String = "git@github.com:test/test-project.git".to_owned(),
        name: String = "test-project".to_owned(),
        default_branch: String = "main".to_owned(),
        project_type: Option<String> = None,
        schema_version: u32 = 1,
        settings: serde_json::Value = serde_json::json!({}),
        created_at: chrono::DateTime<Utc> = Utc::now(),
        updated_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`ProjectFactory`] with sensible defaults.
pub fn a_project() -> ProjectFactory {
    ProjectFactory::new()
}

define_factory! {
    /// Factory for [`KnowledgeItem`] instances.
    pub struct KnowledgeItemFactory for KnowledgeItem {
        id: KnowledgeItemId = KnowledgeItemId::new(),
        project_id: ProjectId = ProjectId::new(),
        principal_id: PrincipalId = PrincipalId::new(),
        kind: KnowledgeKind = KnowledgeKind::Heuristic,
        content: String = "test knowledge content".to_owned(),
        tags: Vec<String> = Vec::new(),
        confidence: Confidence = Confidence::Inferred,
        claim_context: Option<serde_json::Value> = None,
        source_context: serde_json::Value = serde_json::json!({}),
        episode_id: Option<tribal_domain::EpisodeId> = None,
        capture_commit: Option<String> = None,
        capture_branch: Option<String> = None,
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`KnowledgeItemFactory`] with sensible defaults.
pub fn a_knowledge_item() -> KnowledgeItemFactory {
    KnowledgeItemFactory::new()
}

define_factory! {
    /// Factory for [`Job`] instances.
    ///
    /// Defaults to `Queued` status with `None` outcome, respecting the
    /// status/outcome invariant.
    pub struct JobFactory for Job {
        id: JobId = JobId::new(),
        correlation_id: Option<tribal_domain::EpisodeId> = None,
        project_id: ProjectId = ProjectId::new(),
        principal_id: PrincipalId = PrincipalId::new(),
        actor_id: Option<PrincipalId> = None,
        status: JobStatus = JobStatus::Queued,
        outcome: Option<tribal_domain::JobOutcome> = None,
        batch_size: Option<u32> = None,
        committed_batch_id: Option<RelationBatchId> = None,
        source_context: serde_json::Value = serde_json::json!({}),
        extraction_original_count: Option<u32> = None,
        error_message: Option<String> = None,
        extraction_prompt_version_id: PromptVersionId = PromptVersionId::new(),
        triage_prompt_version_id: PromptVersionId = PromptVersionId::new(),
        relation_prompt_version_id: PromptVersionId = PromptVersionId::new(),
        trace_context: Option<String> = None,
        completed_at: Option<chrono::DateTime<Utc>> = None,
        created_at: chrono::DateTime<Utc> = Utc::now(),
        updated_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`JobFactory`] with sensible defaults.
pub fn a_job() -> JobFactory {
    JobFactory::new()
}

define_factory! {
    /// Factory for [`Reference`] instances.
    pub struct ReferenceFactory for Reference {
        id: ReferenceId = ReferenceId::new(),
        knowledge_item_id: KnowledgeItemId = KnowledgeItemId::new(),
        kind: ReferenceKind = ReferenceKind::FilePath,
        value: String = "//src/lib.rs".to_owned(),
        description: Option<String> = None,
        project_id: ProjectId = ProjectId::new(),
        commit: Option<String> = None,
        branch: Option<String> = None,
    }
}

/// Returns a [`ReferenceFactory`] with sensible defaults.
pub fn a_reference() -> ReferenceFactory {
    ReferenceFactory::new()
}

define_factory! {
    /// Factory for [`Embedding`] instances.
    pub struct EmbeddingFactory for Embedding {
        id: EmbeddingId = EmbeddingId::new(),
        knowledge_item_id: KnowledgeItemId = KnowledgeItemId::new(),
        model: String = "nomic-embed-text:v1.5".to_owned(),
        dimensions: u32 = 384,
        embedding: Vec<f32> = vec![0.0; 384],
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns an [`EmbeddingFactory`] with sensible defaults.
pub fn a_embedding() -> EmbeddingFactory {
    EmbeddingFactory::new()
}

define_factory! {
    /// Factory for [`KnowledgeItemRelation`] instances.
    pub struct KnowledgeItemRelationFactory for KnowledgeItemRelation {
        id: RelationId = RelationId::new(),
        relation_batch_id: RelationBatchId = RelationBatchId::new(),
        source_id: KnowledgeItemId = KnowledgeItemId::new(),
        target_id: KnowledgeItemId = KnowledgeItemId::new(),
        relation_type: RelationKind = RelationKind::Supports,
        principal_id: PrincipalId = PrincipalId::new(),
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`KnowledgeItemRelationFactory`] with sensible defaults.
pub fn a_knowledge_item_relation() -> KnowledgeItemRelationFactory {
    KnowledgeItemRelationFactory::new()
}

define_factory! {
    /// Factory for [`ItemObservation`] instances.
    pub struct ItemObservationFactory for ItemObservation {
        id: ItemObservationId = ItemObservationId::new(),
        knowledge_item_id: KnowledgeItemId = KnowledgeItemId::new(),
        principal_id: PrincipalId = PrincipalId::new(),
        source_type: SourceType = SourceType::AgentMediated,
        observed_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns an [`ItemObservationFactory`] with sensible defaults.
pub fn a_item_observation() -> ItemObservationFactory {
    ItemObservationFactory::new()
}

define_factory! {
    /// Factory for [`TriageSimilarItemDecision`] instances.
    pub struct TriageSimilarItemDecisionFactory for TriageSimilarItemDecision {
        id: TriageSimilarItemDecisionId = TriageSimilarItemDecisionId::new(),
        job_id: JobId = JobId::new(),
        batch_index: u32 = 0,
        matched_item_id: KnowledgeItemId = KnowledgeItemId::new(),
        similarity_score: f32 = 0.85,
        suggested_relation: RelationSuggestion = RelationSuggestion::Supports,
        justification_text: String = "test justification".to_owned(),
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`TriageSimilarItemDecisionFactory`] with sensible defaults.
pub fn a_triage_similar_item_decision() -> TriageSimilarItemDecisionFactory {
    TriageSimilarItemDecisionFactory::new()
}

define_factory! {
    /// Factory for [`TriageResult`] instances.
    ///
    /// Use the outcome-specific entry points instead: [`a_triage_result_created`],
    /// [`a_triage_result_duplicate`], or [`a_triage_result_failed`].
    pub struct TriageResultFactory for TriageResult {
        id: TriageResultId = TriageResultId::new(),
        job_id: JobId = JobId::new(),
        batch_index: u32 = 0,
        similar_items: Vec<SimilarItem> = Vec::new(),
        created_at: chrono::DateTime<Utc> = Utc::now(),
        outcome: TriageOutcome = TriageOutcome::Created { item_id: KnowledgeItemId::new() },
    }
}

/// Returns a [`TriageResultFactory`] with a `Created` outcome.
pub fn a_triage_result_created() -> TriageResultFactory {
    TriageResultFactory::new()
}

/// Returns a [`TriageResultFactory`] with a `Duplicate` outcome.
pub fn a_triage_result_duplicate() -> TriageResultFactory {
    TriageResultFactory::new().outcome(TriageOutcome::Duplicate {
        observation_id: ItemObservationId::new(),
        matched_item_id: KnowledgeItemId::new(),
    })
}

/// Returns a [`TriageResultFactory`] with a `Failed` outcome.
pub fn a_triage_result_failed() -> TriageResultFactory {
    TriageResultFactory::new().outcome(TriageOutcome::Failed {
        error_message: "test failure".to_owned(),
        retryable: false,
    })
}

define_factory! {
    /// Factory for [`RetrievalFeedback`] instances.
    pub struct RetrievalFeedbackFactory for RetrievalFeedback {
        id: RetrievalFeedbackId = RetrievalFeedbackId::new(),
        trace_id: String = "00000000000000000000000000000001".to_owned(),
        query_text: String = "test query".to_owned(),
        embedding_model: String = "nomic-embed-text:v1.5".to_owned(),
        returned_item_ids: Vec<KnowledgeItemId> = Vec::new(),
        explored_anchor_ids: Vec<KnowledgeItemId> = Vec::new(),
        policy_version: Option<String> = None,
        principal_id: PrincipalId = PrincipalId::new(),
        rating: FeedbackRating = FeedbackRating::Positive,
        notes: Option<String> = None,
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`RetrievalFeedbackFactory`] with sensible defaults.
pub fn a_retrieval_feedback() -> RetrievalFeedbackFactory {
    RetrievalFeedbackFactory::new()
}

define_factory! {
    /// Factory for [`AuthToken`] instances.
    pub struct AuthTokenFactory for AuthToken {
        id: AuthTokenId = AuthTokenId::new(),
        token_hash: String = "a".repeat(64),
        principal_id: PrincipalId = PrincipalId::new(),
        expires_at: chrono::DateTime<Utc> = Utc::now() + chrono::Duration::hours(24),
        created_at: chrono::DateTime<Utc> = Utc::now(),
        revoked_at: Option<chrono::DateTime<Utc>> = None,
    }
}

/// Returns an [`AuthTokenFactory`] with sensible defaults.
pub fn a_auth_token() -> AuthTokenFactory {
    AuthTokenFactory::new()
}

define_factory! {
    /// Factory for [`PromptVersion`] instances.
    pub struct PromptVersionFactory for PromptVersion {
        id: PromptVersionId = PromptVersionId::new(),
        stage: PromptStage = PromptStage::Extraction,
        content_hash: String = "b".repeat(64),
        content: String = "test prompt content".to_owned(),
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`PromptVersionFactory`] with sensible defaults.
pub fn a_prompt_version() -> PromptVersionFactory {
    PromptVersionFactory::new()
}

define_factory! {
    /// Factory for [`TokenUsage`] instances.
    pub struct TokenUsageFactory for TokenUsage {
        id: TokenUsageId = TokenUsageId::new(),
        job_id: Option<JobId> = None,
        task_id: Option<TaskId> = None,
        attempt: i32 = 0,
        stage: PipelineStage = PipelineStage::Extraction,
        purpose: Option<tribal_domain::EmbeddingPurpose> = None,
        provider: String = "test-provider".to_owned(),
        model: String = "test-model".to_owned(),
        tokens_input: i32 = 100,
        tokens_output: i32 = 50,
        tokens_cache_read: i32 = 0,
        tokens_cache_write: i32 = 0,
        tokens_total: i32 = 150,
        latency_ms: i32 = 200,
        prompt_version_id: Option<PromptVersionId> = None,
        trace_id: Option<String> = None,
        created_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`TokenUsageFactory`] with sensible defaults.
pub fn a_token_usage() -> TokenUsageFactory {
    TokenUsageFactory::new()
}

define_factory! {
    /// Factory for [`Task`] instances.
    pub struct TaskFactory for Task {
        id: TaskId = TaskId::new(),
        job_id: JobId = JobId::new(),
        task_type: TaskType = TaskType::Extraction,
        status: TaskStatus = TaskStatus::Queued,
        batch_index: Option<u32> = None,
        claim_token: Option<uuid::Uuid> = None,
        available_at: chrono::DateTime<Utc> = Utc::now(),
        claimed_by: Option<String> = None,
        claimed_at: Option<chrono::DateTime<Utc>> = None,
        heartbeat_at: Option<chrono::DateTime<Utc>> = None,
        retry_count: u32 = 0,
        error_kind: Option<tribal_domain::TaskErrorKind> = None,
        error_message: Option<String> = None,
        created_at: chrono::DateTime<Utc> = Utc::now(),
        updated_at: chrono::DateTime<Utc> = Utc::now(),
    }
}

/// Returns a [`TaskFactory`] with sensible defaults.
pub fn a_task() -> TaskFactory {
    TaskFactory::new()
}

define_factory! {
    /// Factory for [`Standing`] instances.
    pub struct StandingFactory for Standing {
        supporting_count: u32 = 0,
        contradicting_count: u32 = 0,
        superseded_by: Option<KnowledgeItemId> = None,
        observation_count: u32 = 1,
        newest_supporting_id: Option<KnowledgeItemId> = None,
        newest_contradicting_id: Option<KnowledgeItemId> = None,
        supporting_episode_count: u32 = 0,
        supporting_project_count: u32 = 0,
    }
}

/// Returns a [`StandingFactory`] with sensible defaults.
pub fn a_standing() -> StandingFactory {
    StandingFactory::new()
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_principal_builds_with_defaults() {
        let p = a_principal().build();
        assert_eq!(p.principal_key(), "user:test");
        assert!(p.display_name().is_none());
    }

    #[test]
    fn a_tag_registry_entry_builds_with_defaults() {
        let t = a_tag_registry_entry().build();
        assert_eq!(t.tag(), "test-tag");
    }

    #[test]
    fn a_similar_item_builds_with_defaults() {
        let s = a_similar_item().build();
        assert!((s.similarity_score() - 0.85).abs() < f32::EPSILON);
        assert_eq!(s.suggested_relation(), RelationSuggestion::Supports);
    }

    #[test]
    fn a_project_builds_with_defaults() {
        let project = a_project().build();
        assert_eq!(project.name(), "test-project");
        assert_eq!(project.default_branch(), "main");
    }

    #[test]
    fn a_project_allows_field_override() {
        let project = a_project().name("custom".to_owned()).build();
        assert_eq!(project.name(), "custom");
        assert_eq!(project.default_branch(), "main");
    }

    #[test]
    fn a_knowledge_item_builds_with_defaults() {
        let item = a_knowledge_item().build();
        assert_eq!(item.kind(), KnowledgeKind::Heuristic);
        assert_eq!(item.content(), "test knowledge content");
        assert_eq!(item.confidence(), Confidence::Inferred);
    }

    #[test]
    fn a_job_builds_with_defaults() {
        let job = a_job().build();
        assert_eq!(job.status(), JobStatus::Queued);
        assert!(job.outcome().is_none());
    }

    #[test]
    fn a_reference_builds_with_defaults() {
        let r = a_reference().build();
        assert_eq!(r.kind(), ReferenceKind::FilePath);
        assert_eq!(r.value(), "//src/lib.rs");
    }

    #[test]
    fn a_embedding_builds_with_defaults() {
        let e = a_embedding().build();
        assert_eq!(e.model(), "nomic-embed-text:v1.5");
        assert_eq!(e.dimensions(), 384);
        assert_eq!(e.embedding().len(), 384);
    }

    #[test]
    fn a_knowledge_item_relation_builds_with_defaults() {
        let r = a_knowledge_item_relation().build();
        assert_eq!(r.relation_type(), RelationKind::Supports);
    }

    #[test]
    fn a_item_observation_builds_with_defaults() {
        let o = a_item_observation().build();
        assert_eq!(o.source_type(), SourceType::AgentMediated);
    }

    #[test]
    fn a_triage_similar_item_decision_builds_with_defaults() {
        let d = a_triage_similar_item_decision().build();
        assert_eq!(d.suggested_relation(), RelationSuggestion::Supports);
        assert_eq!(d.justification_text(), "test justification");
    }

    #[test]
    fn a_triage_result_created_builds_with_defaults() {
        let r = a_triage_result_created().build();
        assert!(matches!(r.outcome(), TriageOutcome::Created { .. }));
    }

    #[test]
    fn a_triage_result_duplicate_builds_with_defaults() {
        let r = a_triage_result_duplicate().build();
        assert!(matches!(r.outcome(), TriageOutcome::Duplicate { .. }));
    }

    #[test]
    fn a_triage_result_failed_builds_with_defaults() {
        let r = a_triage_result_failed().build();
        assert!(matches!(
            r.outcome(),
            TriageOutcome::Failed {
                retryable: false,
                ..
            }
        ));
    }

    #[test]
    fn a_retrieval_feedback_builds_with_defaults() {
        let f = a_retrieval_feedback().build();
        assert_eq!(f.rating(), FeedbackRating::Positive);
        assert_eq!(f.query_text(), "test query");
    }

    #[test]
    fn a_auth_token_builds_with_defaults() {
        let t = a_auth_token().build();
        assert_eq!(t.token_hash().len(), 64);
        assert!(t.revoked_at().is_none());
    }

    #[test]
    fn a_prompt_version_builds_with_defaults() {
        let pv = a_prompt_version().build();
        assert_eq!(pv.stage(), PromptStage::Extraction);
        assert_eq!(pv.content(), "test prompt content");
    }

    #[test]
    fn a_token_usage_builds_with_defaults() {
        let tu = a_token_usage().build();
        assert_eq!(tu.stage(), PipelineStage::Extraction);
        assert_eq!(tu.tokens_total(), 150);
    }

    #[test]
    fn a_task_builds_with_defaults() {
        let t = a_task().build();
        assert_eq!(t.task_type(), TaskType::Extraction);
        assert_eq!(t.status(), TaskStatus::Queued);
        assert_eq!(t.retry_count(), 0);
    }

    #[test]
    fn a_standing_builds_with_defaults() {
        let s = a_standing().build();
        assert_eq!(s.supporting_count(), 0);
        assert_eq!(s.observation_count(), 1);
        assert!(s.superseded_by().is_none());
    }
}
