[package]
name = "tribal-server"
edition.workspace = true
version.workspace = true
license-file.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
thiserror.workspace = true
tribal-config.workspace = true
tribal-domain.workspace = true
tribal-mcp.workspace = true
tribal-worker.workspace = true
tribal-telemetry.workspace = true
