[package]
name = "tribal-ui"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anstream.workspace = true
anstyle.workspace = true
chrono.workspace = true
chrono-humanize.workspace = true
supports-color.workspace = true
termbg.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
